repos:
  - hooks:
      - id: sync-uv-pre-commit
        args:
          - "-a ruff:ruff:v:"
          - "-a ruff:ruff-format:v:"
          - "-g dev"
    repo: https://github.com/phi-friday/sync-uv-pre-commit
    rev: v0.6.3

  - hooks:
      - id: ruff
        name: ruff-lint
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10

  - hooks:
      - id: pyright
        entry: pyright
        pass_filenames: false
        types: [python]
        args:
          - "--pythonpath=.venv/bin/python"
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396