version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs
    - |
      export SITE_NAME="typed-diskcache $READTHEDOCS_VERSION"
      export NO_COLOR=1
      uv run mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html